import * as React from "react";
import { useRouter } from "next/router";
import { BlogService } from "../../api/service";
import { PostDTO } from "./../../Components/Item/post.dto";
import Head from "next/head";
import { Header } from "../../Components/Header/header";
import { Layout } from "../../Components/Layout/layout";
import Footer from "./../../Components/Footer/footer";

export interface IPostsItemProps {
  _id?: any;
  title?: string;
  tag?: [];
  highlight?: boolean;
  time?: any;
}
export async function getStaticPaths() {
  let posts = await BlogService.getPosts();
  const paths = posts.data.map((post: IPostsItemProps) => ({
    params: { postId: post._id },
  }));
  return {
    paths,
    fallback: true, // can also be true or 'blocking'
  };
}

export async function getStaticProps(context: any) {
  let post = await BlogService.getPost(context?.params.postId);
  return {
    props: {
      post: post.data,
    },
  };
}
export default function PostsItem(props: any) {
  const router = useRouter();
  // console.log({ router, props });
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout>
        <div className="post">
          <p className="post-title">{props.post.title}</p>
        </div>
        ;
      </Layout>
      <Footer />
    </>
  );
}
