import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { Col, Row } from "react-bootstrap";
import Footer from "../Components/Footer/footer";
import { Header } from "../Components/Header/header";
import { Item } from "../Components/Item/item";
import { Layout } from "../Components/Layout/layout";
import { BlogService } from "./../api/service";
import { Enum } from "./../Enum/enum";

export async function getStaticProps() {
  let posts = await BlogService.getPosts();
  // await posts.json()
  return {
    props: {
      posts: posts.data,
    },
  };
}

const Home: NextPage = (props: any) => {
  console.log(props);
  useEffect(() => {
    const getTheme = localStorage.getItem("theme");
    if (Boolean(getTheme) === false) {
      localStorage.setItem("theme", Enum.theme.light);
      document
        .getElementsByTagName("HTML")[0]
        .setAttribute("theme", Enum.theme.light);
    } else {
      document
        .getElementsByTagName("HTML")[0]
        .setAttribute("theme", getTheme || Enum.theme.light);
    }
  }, []);
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout>
        <ul>
          <Row>
            {props.posts.map((i: object) => (
              <Col lg={6}>
                <Item item={i} />
              </Col>
            ))}
          </Row>
        </ul>
      </Layout>
      <Footer />
    </>
  );
};

export default Home;
