import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../Components/Footer/footer";
import { Header } from "../Components/Header/header";
import { Layout } from "../Components/Layout/layout";
import { BlogService } from "./../api/service";
import axios from "axios";
import { useEffect } from "react";
import { Enum } from "./../Enum/enum";

export const getStaticProps = async () => {
  const posts = await fetch("http://localhost:8000/posts");
  console.log(posts);
  // });
  return {
    props: {
      posts: posts.toString(),
    },
  };
};
const Home: NextPage = (props) => {
  console.log(props);
  useEffect(() => {
    const getTheme = localStorage.getItem("theme");
    if (Boolean(getTheme) === false) {
      localStorage.setItem("theme", Enum.theme.light);
      document
        .getElementsByTagName("HTML")[0]
        .setAttribute("theme", Enum.theme.light);
    } else {
      document
        .getElementsByTagName("HTML")[0]
        .setAttribute("theme", getTheme || Enum.theme.light);
    }
  }, []);
  return (
    <Layout>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Footer />
    </Layout>
  );
};

export default Home;
